// 觅食迹 - 店铺数据
// 蛇口地区美食店铺数据

const foodData = require('./foodData')

module.exports = {
  // 初始店铺数据
  shops: [
    {
      id: 1,
      name: '百草堂糖水',
      emoji: '🍵',
      rating: 4.8,
      price: 30,
      category: '粤菜',
      tags: ['老字号', '糖水', '蛇口'],
      address: '南山区蛇口街道渔村路43号',
      lat: 22.4862,
      lng: 113.9021,
      hours: '09:00-22:00',
      dishes: ['杨枝甘露', '双皮奶', '龟苓膏'],
      phone: '0755-26832856',
      logo: '/images/百草堂糖水.jpg',
      checkInCount: 328,
      wantCount: 156
    },
    {
      id: 2,
      name: '宝狮杂碎小食馆',
      emoji: '🥡',
      rating: 4.6,
      price: 45,
      category: '粤菜',
      tags: ['港式', '小食', '老字号'],
      address: '南山区蛇口街道老街38号',
      lat: 22.4848,
      lng: 113.9042,
      hours: '10:00-21:00',
      dishes: ['杂碎面', '咖喱鱼蛋', '西多士'],
      phone: '0755-26821547',
      logo: '/images/宝狮杂碎小食馆.jpg',
      checkInCount: 214,
      wantCount: 98
    },
    {
      id: 3,
      name: '嘉华小吃',
      emoji: '🥟',
      rating: 4.7,
      price: 35,
      category: '粤菜',
      tags: ['粤菜', '小吃', '老字号', '早茶'],
      address: '南山区蛇口街道湾厦路22号',
      lat: 22.4828,
      lng: 113.9068,
      hours: '07:00-14:00, 17:00-20:00',
      dishes: ['虾饺', '烧麦', '肠粉'],
      phone: '0755-26830985',
      logo: '/images/嘉华小吃.jpg',
      checkInCount: 276,
      wantCount: 132
    },
    {
      id: 4,
      name: '揭阳老五粿条汤',
      emoji: '🍜',
      rating: 4.5,
      price: 28,
      category: '粤菜',
      tags: ['潮汕', '粿条', '老字号'],
      address: '南山区蛇口街道渔村路52号',
      lat: 22.4856,
      lng: 113.9015,
      hours: '06:30-14:00',
      dishes: ['牛肉粿条', '粿条汤', '手打牛肉丸'],
      phone: '0755-26693621',
      logo: '/images/揭阳老五粿条汤.jpg',
      checkInCount: 189,
      wantCount: 87
    },
    {
      id: 5,
      name: '老兵牛蹄店',
      emoji: '🦶',
      rating: 4.9,
      price: 80,
      category: '粤菜',
      tags: ['特色', '牛蹄', '必吃', '老字号'],
      address: '南山区蛇口街道蛇口老街15号',
      lat: 22.4839,
      lng: 113.9038,
      hours: '11:00-14:00, 17:00-21:00',
      dishes: ['卤牛蹄', '牛杂', '凉拌牛腱'],
      phone: '0755-26812895',
      logo: '/images/老兵牛蹄店.jpg',
      checkInCount: 512,
      wantCount: 248
    },
    {
      id: 6,
      name: '蛇口德记烧腊饭店',
      emoji: '🍗',
      rating: 4.6,
      price: 50,
      category: '粤菜',
      tags: ['烧腊', '老字号', '港式'],
      address: '南山区蛇口街道渔村路28号',
      lat: 22.4858,
      lng: 113.9019,
      hours: '10:30-21:30',
      dishes: ['烧鹅', '叉烧', '白切鸡'],
      phone: '0755-26823789',
      logo: '/images/蛇口德记烧腊饭店.jpg',
      checkInCount: 367,
      wantCount: 178
    },
    {
      id: 7,
      name: '益坊鹅品',
      emoji: '🦢',
      rating: 4.7,
      price: 60,
      category: '粤菜',
      tags: ['鹅', '潮汕', '打冷'],
      address: '南山区蛇口街道湾厦路35号',
      lat: 22.4832,
      lng: 113.9058,
      hours: '11:00-22:00',
      dishes: ['卤水鹅', '鹅肠', '鹅肝'],
      phone: '0755-26842895',
      logo: '/images/益坊鹅店.jpg',
      checkInCount: 298,
      wantCount: 143
    },
    {
      id: 8,
      name: '林鲜记鸡煲',
      emoji: '🍗',
      rating: 4.8,
      price: 55,
      category: '粤菜',
      tags: ['鸡煲', '宵夜', '蛇口'],
      address: '南山区蛇口街道蛇口新街88号',
      lat: 22.4872,
      lng: 113.9028,
      hours: '17:00-02:00',
      dishes: ['椰子鸡煲', '榴莲鸡煲', '田螺鸡煲'],
      phone: '0755-26857321',
      logo: '/images/林鲜记鸡煲.jpg',
      checkInCount: 445,
      wantCount: 212
    },
    {
      id: 9,
      name: '康乐鱼仔档',
      emoji: '🐟',
      rating: 4.5,
      price: 65,
      category: '粤菜',
      tags: ['海鲜', '鱼仔', '大排档'],
      address: '南山区蛇口街道康乐路23号',
      lat: 22.4892,
      lng: 113.9045,
      hours: '17:00-23:00',
      dishes: ['咸鱼蒸肉饼', '鱼仔煲', '椒盐鱿鱼'],
      phone: '0755-26838476',
      logo: '/images/康乐鱼仔档.jpg',
      checkInCount: 176,
      wantCount: 89
    },
    {
      id: 10,
      name: '佳俊八宝牛杂',
      emoji: '🥘',
      rating: 4.6,
      price: 40,
      category: '小吃',
      tags: ['牛杂', '街头小吃'],
      address: '南山区蛇口街道新街路18号',
      lat: 22.4851,
      lng: 113.9028,
      hours: '11:00-22:00',
      dishes: ['牛杂煲', '萝卜牛杂', '咖喱牛杂'],
      phone: '0755-26821984',
      logo: '/images/佳俊八宝牛杂.jpg',
      checkInCount: 234,
      wantCount: 118
    },
    {
      id: 11,
      name: '中山壹鸽',
      emoji: '🕊️',
      rating: 4.7,
      price: 70,
      category: '粤菜',
      tags: ['鸽子', '中山', '特色'],
      address: '南山区蛇口街道工业区路6号',
      lat: 22.4812,
      lng: 113.9082,
      hours: '11:00-14:00, 17:00-21:00',
      dishes: ['红烧乳鸽', '盐焗鸽', '鸽汤'],
      phone: '0755-26876234',
      logo: '/images/中山壹鸽.jpg',
      checkInCount: 321,
      wantCount: 167
    },
    {
      id: 12,
      name: '老顾客煲仔饭',
      emoji: '🍚',
      rating: 4.8,
      price: 45,
      category: '粤菜',
      tags: ['煲仔饭', '老字号', '必吃'],
      address: '南山区蛇口街道渔村路68号',
      lat: 22.4868,
      lng: 113.9012,
      hours: '11:00-14:00, 17:00-21:00',
      dishes: ['腊味煲仔饭', '黄鳝煲仔饭', '滑鸡煲仔饭'],
      phone: '0755-26845238',
      logo: '/images/老顾客煲仔饭.jpg',
      checkInCount: 489,
      wantCount: 236
    },
    {
      id: 13,
      name: '小致臭豆腐',
      emoji: '🧈',
      rating: 4.3,
      price: 20,
      category: '小吃',
      tags: ['臭豆腐', '街头小吃'],
      address: '南山区蛇口街道步行街17号',
      lat: 22.4842,
      lng: 113.9048,
      hours: '15:00-23:00',
      dishes: ['香辣臭豆腐', '原味臭豆腐', '臭豆腐煲'],
      phone: '0755-26819823',
      logo: '/images/小致臭豆腐.jpg',
      checkInCount: 143,
      wantCount: 62
    },
    {
      id: 14,
      name: '姐妹手作',
      emoji: '🧁',
      rating: 4.9,
      price: 55,
      category: '其他',
      tags: ['甜品', '手工', '下午茶'],
      address: '南山区蛇口街道海上世界A区',
      lat: 22.4798,
      lng: 113.9125,
      hours: '12:00-22:00',
      dishes: ['芒果班戟', '杨枝甘露', '榴莲忘返'],
      phone: '0755-26856321',
      logo: '/images/姐妹手作（蛇口）.jpg',
      checkInCount: 567,
      wantCount: 289
    },
    {
      id: 15,
      name: '好好味面馆',
      emoji: '🍜',
      rating: 4.7,
      price: 35,
      category: '粤菜',
      tags: ['老字号', '19年', '面馆', '南山区'],
      address: '南山区桃园路92-2号（近天虹商场）',
      lat: 22.5312,
      lng: 113.9299,
      hours: '07:00-22:00',
      dishes: ['牛腩捞面', '净云吞', '猪脚姜醋蛋'],
      phone: '',
      logo: '/images/好好味面馆（桃园路）.jpg',
      checkInCount: 356,
      wantCount: 198
    },
    {
      id: 16,
      name: '翠湖广东乡下菜',
      emoji: '🥘',
      rating: 4.6,
      price: 65,
      category: '粤菜',
      tags: ['老字号', '16年', '农家菜', '南山区'],
      address: '南山区龙珠四路龙井村西区103号',
      lat: 22.5380,
      lng: 113.9350,
      hours: '11:00-14:00, 17:00-21:30',
      dishes: ['吊烧鸡', '台山黄鳝饭', '自磨黑豆腐'],
      phone: '',
      logo: '/images/翠湖广东乡下菜.jpg',
      checkInCount: 267,
      wantCount: 134
    },
    {
      id: 17,
      name: '老字号德记烧腊',
      emoji: '🍗',
      rating: 4.7,
      price: 55,
      category: '粤菜',
      tags: ['老字号', '20年', '烧腊', '南山区'],
      address: '南山区南水路南水步行街55号',
      lat: 22.4850,
      lng: 113.9015,
      hours: '07:30-20:30',
      dishes: ['金牌烧鹅', '海鲜来料加工', '蜜汁叉烧'],
      phone: '',
      logo: '/images/老字号德记烧腊.jpg',
      checkInCount: 198,
      wantCount: 96
    },
    {
      id: 18,
      name: '小煵记',
      emoji: '🦐',
      rating: 4.5,
      price: 85,
      category: '粤菜',
      tags: ['老字号', '16年', '本地菜', '南山区'],
      address: '南山区蛇口新路1173号',
      lat: 22.4865,
      lng: 113.9050,
      hours: '11:00-14:00, 17:00-次日01:30',
      dishes: ['豉油皇大虾', '椒盐九肚鱼', '豆豉鸡'],
      phone: '',
      logo: '/images/小煵记.深圳本地菜.jpg',
      checkInCount: 312,
      wantCount: 156
    },
    {
      id: 19,
      name: '湛记佬海鲜',
      emoji: '🦀',
      rating: 4.8,
      price: 120,
      category: '粤菜',
      tags: ['老字号', '19年', '海鲜', '南山区'],
      address: '南山区白石洲中路14号',
      lat: 22.5480,
      lng: 113.9180,
      hours: '11:00-14:00, 17:00-次日03:00',
      dishes: ['椒盐濑尿虾', '盐焗鹅掌翼', '紫苏拍蒜炒波龙'],
      phone: '',
      logo: '/images/湛记佬海鲜.老字号·深圳19年老字号餐厅.jpg',
      checkInCount: 423,
      wantCount: 215
    },
    {
      id: 20,
      name: '海燕餐厅',
      emoji: '🦞',
      rating: 4.7,
      price: 150,
      category: '粤菜',
      tags: ['老字号', '20年', '海鲜', '海上世界'],
      address: '南山区望海路海上世界B区小木屋',
      lat: 22.4798,
      lng: 113.9125,
      hours: '10:00-次日01:00',
      dishes: ['黑松露鲍鱼焖鸡', '蒜蓉粉丝九节虾', '黑胡椒炒蟹'],
      phone: '',
      logo: '/images/海燕餐厅（海上世界店）.jpg',
      checkInCount: 387,
      wantCount: 203
    },
    {
      id: 21,
      name: '蛇口老街鱼仔档',
      emoji: '🐟',
      rating: 4.8,
      price: 70,
      category: '粤菜',
      tags: ['老字号', '20年', '鱼仔', '蛇口'],
      address: '南山区蛇口老街143-7号',
      lat: 22.4842,
      lng: 113.9035,
      hours: '10:30-次日02:30',
      dishes: ['椒盐九肚鱼', '蚝仔烙', '椒盐濑尿虾'],
      phone: '',
      logo: '/images/蛇口老街鱼仔档.jpg',
      checkInCount: 456,
      wantCount: 234
    },
    {
      id: 22,
      name: '华洋酒楼',
      emoji: '🥟',
      rating: 4.6,
      price: 60,
      category: '粤菜',
      tags: ['老字号', '20年', '广式茶点', '水湾'],
      address: '南山区水湾路华洋大厦一楼',
      lat: 22.4840,
      lng: 113.9080,
      hours: '08:00-14:00, 17:00-22:00',
      dishes: ['华洋虾饺皇', '豉汁凤爪', '风味牛肚'],
      phone: '',
      logo: '/images/华洋酒楼.jpg',
      checkInCount: 289,
      wantCount: 145
    },
    {
      id: 23,
      name: '新高记湛江鸡饭店',
      emoji: '🍗',
      rating: 4.5,
      price: 45,
      category: '粤菜',
      tags: ['老字号', '16年', '湛江鸡', '南山区'],
      address: '南山区南头街道龙大新路90号',
      lat: 22.5350,
      lng: 113.9280,
      hours: '10:00-22:00',
      dishes: ['招牌湛江白切鸡', '手工乡下捞粉', '青橄榄猪肺'],
      phone: '',
      logo: '/images/新高记湛江鸡饭店（南头古城店）.jpg',
      checkInCount: 245,
      wantCount: 128
    },
    {
      id: 24,
      name: '头牌小厨·蛇口大排档',
      emoji: '🍽️',
      rating: 4.7,
      price: 85,
      category: '粤菜',
      tags: ['大排档', '粤式', '热门榜第1', '蛇口'],
      address: '南山区招商街道太子路83号发胜大楼107-6',
      lat: 22.4875,
      lng: 113.9155,
      hours: '11:00-14:00 17:00-23:00',
      dishes: ['茂名捞粉', '白切粉肠', '五柳炸蛋', '盐焗海螺', '蚝绿嗨', '捞汁鱼皮', '姜酒焗牛肉', '椒盐骨鳝', '话梅大肠', '菜汁酿豆腐', '啫啫沙姜果园鸡', '燕麦反沙芋头'],
      phone: '',
      logo: '/images/头牌小厨.jpg',
      checkInCount: 523,
      wantCount: 267
    }
  ],

  // 店铺名称别名映射（用于攻略文本识别）
  shopNameMap: {
    '百草堂': '百草堂糖水',
    '草堂': '百草堂糖水',
    '宝狮': '宝狮杂碎小食馆',
    '宝狮杂碎': '宝狮杂碎小食馆',
    '杂碎': '宝狮杂碎小食馆',
    '嘉华': '嘉华小吃',
    '揭阳老五': '揭阳老五粿条汤',
    '老五': '揭阳老五粿条汤',
    '粿条': '揭阳老五粿条汤',
    '老兵': '老兵牛蹄店',
    '牛蹄': '老兵牛蹄店',
    '德记': '蛇口德记烧腊饭店',
    '烧腊': '蛇口德记烧腊饭店',
    '德记烧腊': '蛇口德记烧腊饭店',
    '益坊': '益坊鹅品',
    '鹅品': '益坊鹅品',
    '林鲜记': '林鲜记鸡煲',
    '鸡煲': '林鲜记鸡煲',
    '康乐鱼仔': '康乐鱼仔档',
    '鱼仔': '康乐鱼仔档',
    '佳俊': '佳俊八宝牛杂',
    '八宝牛杂': '佳俊八宝牛杂',
    '牛杂': '佳俊八宝牛杂',
    '中山壹鸽': '中山壹鸽',
    '壹鸽': '中山壹鸽',
    '老顾客': '老顾客煲仔饭',
    '煲仔饭': '老顾客煲仔饭',
    '小致': '小致臭豆腐',
    '臭豆腐': '小致臭豆腐',
    '姐妹手作': '姐妹手作',
    '姐妹': '姐妹手作',
    // 新增店铺 (ID 14-22)
    '好好味': '好好味面馆',
    '好好味面馆': '好好味面馆',
    '翠湖': '翠湖广东乡下菜',
    '翠湖乡下菜': '翠湖广东乡下菜',
    '广东乡下菜': '翠湖广东乡下菜',
    '小煵记': '小煵记',
    '煵记': '小煵记',
    '湛记': '湛记佬海鲜',
    '湛记佬': '湛记佬海鲜',
    '佬海鲜': '湛记佬海鲜',
    '老街鱼仔档': '蛇口老街鱼仔档',
    '鱼仔档': '蛇口老街鱼仔档',
    '海燕': '海燕餐厅',
    '海燕餐厅': '海燕餐厅',
    '华洋': '华洋酒楼',
    '华洋酒楼': '华洋酒楼',
    '新高记': '新高记湛江鸡饭店',
    '新高记湛江鸡': '新高记湛江鸡饭店',
    '湛江鸡': '新高记湛江鸡饭店',
    '头牌小厨': '头牌小厨·蛇口大排档',
    '头牌': '头牌小厨·蛇口大排档'
  },

  // 分类列表（美团风格美食分类）
  categories: [
    '全部',
    '粤菜',
    '川菜',
    '湘菜',
    '北京菜',
    '东南亚餐',
    '日韩料理',
    '西餐',
    '小吃',
    '其他'
  ],

  // 起点选项
  startPoints: [
    { name: '科技生态园', lat: 22.4785, lng: 113.9155 },
    { name: '东角头', lat: 22.4812, lng: 113.9078 },
    { name: '水湾', lat: 22.4858, lng: 113.9025 },
    { name: '海上世界', lat: 22.4798, lng: 113.9125 },
    { name: '我的位置', type: 'current' }
  ],

  // 深圳全市美食（V2新增，ID: 101-165）
  foods: foodData.foods
}
