module.exports = [
  {
    "emoji": "🌳",
    "id": 100,
    "name": "大佛寺",
    "rating": 4.78,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "闹市禅意",
      "6米铜佛",
      "供灯祈福",
      "寺庙图书馆",
      "古风大片",
      "佛教文物",
      "昼夜双景"
    ],
    "desc": "夜晚亮灯后的大佛寺，金碧辉煌层层叠叠，宛如宫崎骏笔下的‘千与千寻’照进现实，是广州最具梦幻感的夜景地标。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/dd68f5e6515ca08ee6504efc3528d057.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 101,
    "name": "越秀公园",
    "rating": 4.75,
    "district": "越秀",
    "city": "广州",
    "lat": 23.1285,
    "lng": 113.274,
    "tags": [
      "泛舟东秀湖"
    ],
    "desc": "广州的象征就在眼前，五羊石雕讲述着‘五仙骑羊赐穗’的千年传说，是每个来穗游客的第一课。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/bbd355f0-2b92-462b-8ae6-45d29e8dda01.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 102,
    "name": "东山湖公园",
    "rating": 4.75,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "羊城八景",
      "广州塔同框",
      "四季皆景",
      "猫咪成群",
      "划船观城",
      "湖边美术馆",
      "长椅放空"
    ],
    "desc": "春天紫荆花盛开，夏天睡莲铺满湖面，秋天落羽杉变金黄，冬天细叶榕依旧葱郁，四季景色各异，任何时候来都有不同的美。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/307f367a052c448d5745eee7fc721aa6.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 103,
    "name": "五羊雕像",
    "rating": 4.7,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "羊城传说起源",
      "城市官方象征",
      "春日木棉映像",
      "360°拍照打卡",
      "五羊栩栩如生"
    ],
    "desc": "广州别名‘羊城’的由来就在这座雕塑里，五位仙人骑五羊赠稻穗的传说，是每个老广从小听到大的故事。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/2b22889c-663c-4759-b9b3-7dd2494781a7_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 104,
    "name": "广州动物园",
    "rating": 4.77,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "莫奈风火烈鸟",
      "长颈鹿错位拍",
      "爱心金鱼缸",
      "飞禽大观焕新",
      "白虎王者范",
      "狐獴像丁满"
    ],
    "desc": "火烈鸟湖如现实版莫奈花园，粉羽倒映碧水，随手一拍就是油画感大片。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/4ddaed61-f06d-483f-9ef9-814e511aa674.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 105,
    "name": "流花湖公园",
    "rating": 4.75,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "古风秘境",
      "油画步道",
      "泛舟观鸟",
      "鹭鸟天堂",
      "皇家园林",
      "治愈角落",
      "免费开放"
    ],
    "desc": "藏在市中心的欧式‘白宫’，晴天湖面倒影宛如天空之镜，随手一拍就是假装在欧洲的大片，氛围感直接拉满。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/17caf742-065d-456e-b614-260671c4eb48.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 106,
    "name": "中山纪念堂",
    "rating": 4.67,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "中西合璧",
      "无柱空间",
      "经典机位",
      "免费讲解"
    ],
    "desc": "为纪念国父孙中山而建，是广州人心中的精神丰碑，承载着‘天下为公’的民族理想。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/19684d15-b99c-4ab8-b519-665d9703dc9f_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 107,
    "name": "广州石室耶稣圣心大教堂",
    "rating": 4.91,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "全球四座之一",
      "远东巴黎圣母院",
      "七彩光晕",
      "闹中取静",
      "玫瑰窗玄机",
      "神级机位",
      "中西匠艺对话",
      "双塔刺苍穹"
    ],
    "desc": "全球仅有的四座全石结构哥特式教堂之一，与巴黎圣母院齐名，整座建筑由花岗岩砌成，历经150年风雨仍巍然屹立，是世界级建筑遗产的活化石。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/c8ac55d8e44806ebcd296b7c9a04a4eb.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 108,
    "name": "北京路步行街",
    "rating": 4.93,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "古今同框",
      "骑楼如片场",
      "满窗光影",
      "老字号云集"
    ],
    "desc": "全国首创的玻璃栈道，脚下就是从唐宋到民国层层叠压的千年古道遗址，白天看文物肌理，夜晚灯光点亮如踏星河，历史感扑面而来。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/74bfa19e52482896ee480c01cbed1a11.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 109,
    "name": "大夫山森林公园",
    "rating": 4.69,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "骑行天堂",
      "天然氧吧",
      "夏日赏荷",
      "红叶水杉",
      "湖边野餐",
      "亲子设施"
    ],
    "desc": "公园有专属自行车道贯穿全园，坡度平缓，适合全家骑行环湖，租一辆双人车沿湖穿梭在森林与湖光之间，微风拂面，惬意极了。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/d700bb17-8c46-49a1-8d9b-6b3437125e18_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 110,
    "name": "长隆欢乐世界",
    "rating": 4.72,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "六大主题",
      "儿童过山车",
      "高空摆锤",
      "童话拍照",
      "U型滑板"
    ],
    "desc": "超级大摆锤和自由落体项目，也把刺激感拉满，每一次摆动、每一回坠落，都让心跳加速，直呼过瘾！",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/24438354-7cab-412d-ba48-41d3c29ba859_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 111,
    "name": "宝墨园",
    "rating": 4.71,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "古建水乡",
      "亲子天堂",
      "鱼王奇观",
      "玫瑰花海",
      "静谧荷池"
    ],
    "desc": "岭南园林中的活态画卷，古建筑依水而建，一步一景，亭台楼阁错落有致，尽显南国雅韵。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/462afcfd357688729463df70c970f5a.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 112,
    "name": "莲花山旅游区",
    "rating": 4.72,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "人工丹霞",
      "喷雾仙境",
      "登塔远眺",
      "林则徐驻防",
      "燕子岩秘境",
      "城墙迷宫"
    ],
    "desc": "世界最高的箔金望海观音像矗立山巅，面向珠江入海口，香火鼎盛，是粤港澳地区家喻户晓的祈福圣地，许多本地人相信她能‘挡台风’，前来求平安、求子、求财运。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a7438ee0b3b920df4185a96f31e917db.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 113,
    "name": "余荫山房",
    "rating": 4.69,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "岭南名园活化石",
      "满洲窗见奇景",
      "浣红跨绿桥",
      "深柳堂藏珍",
      "穿汉服拍照",
      "八角观景亭"
    ],
    "desc": "广东四大名园之一，也是唯一基本保存原貌的古典园林，堪称岭南园林的活化石。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/e2617bc0001c48eaa097f9bea91cd80d.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 114,
    "name": "长隆野生动物世界",
    "rating": 4.85,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "小火车穿草原",
      "投喂长颈鹿"
    ],
    "desc": "拥有世界上数量最多的白虎种群，超过150只白虎在此生活，生态虎园模拟野外环境，还能观看‘白虎跳水’的震撼科普秀，猛兽跃入水中捕食的瞬间极具视觉冲击。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/9e5dab6d1024f889ff2edbcb0b5a33d0.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 115,
    "name": "广州长隆旅游度假区",
    "rating": 4.72,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "65米俯冲",
      "透明缆车",
      "吉尼斯十环",
      "白虎跳水"
    ],
    "desc": "全球唯一能同时看到大熊猫三胞胎和60余只考拉的地方，亲子游必来打卡。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/4de23b27-3938-4cd7-ad34-742b19477aac.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 116,
    "name": "荔湾湖公园",
    "rating": 4.74,
    "district": "荔湾",
    "city": "广州",
    "lat": 23.126,
    "lng": 113.2365,
    "tags": [
      "荷塘如画",
      "西关风情",
      "游船穿湖",
      "文创小店",
      "静谧长廊",
      "连通老城",
      "免费入园"
    ],
    "desc": "清晨粤剧私伙局在古榕下开唱，阿公阿婆耍太极，孩童追泡泡，市井烟火与诗意共存。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/7968cefe-fe01-4df0-99f6-80784580ac25_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 117,
    "name": "陈家祠堂",
    "rating": 4.87,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "岭南明珠",
      "科举书院",
      "百鸟朝凰",
      "民俗展演",
      "必听讲解",
      "三进九堂",
      "地铁直达",
      "夜拍古建"
    ],
    "desc": "岭南建筑艺术的巅峰之作，集木雕、砖雕、石雕、陶塑、灰塑、铜铁铸与彩绘壁画于一体，被誉为‘岭南建筑明珠’，每一处屋檐墙角都是艺术珍品。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/d01530fe971096056d8eaf74f0d8c919.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 118,
    "name": "沙面岛",
    "rating": 4.85,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "露天建筑博物馆",
      "英法租界历史",
      "撞色洋楼",
      "岸边Live演出",
      "闹市绿洲"
    ],
    "desc": "主街绿荫如盖，百年古榕撑起天然遮阳伞，阳光斑驳洒落，沿江步道微风拂面，是广州最惬意的Citywalk路线之一。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/b94dc0b9-3380-4113-a18b-ae2e45f0a73c_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 119,
    "name": "广州十三行博物馆",
    "rating": 4.77,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "免费免预约"
    ],
    "desc": "国内唯一以‘十三行’命名的专题博物馆，完整呈现清代‘一口通商’下广州作为世界贸易枢纽的辉煌历史，是读懂岭南商业文明的起点。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/c92160f9-2577-4e7c-8b0e-33f34c53e50c.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 120,
    "name": "粤海关博物馆",
    "rating": 4.73,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "百年报时钟",
      "最古老海关楼",
      "16:30亮灯",
      "珠江全景",
      "隐藏彩蛋",
      "互动游戏",
      "复古大片",
      "城市秘境",
      "建筑典范"
    ],
    "desc": "广州人的‘大钟楼’，1916年建成的英制机械钟至今仍在报时，曾是全城时间标准，听钟声仿佛穿越百年。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a769c57ea322db74f119c8be99f4b9db.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 121,
    "name": "永庆坊",
    "rating": 4.87,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "微改造典范",
      "月亮桥亮灯",
      "西关小姐传说",
      "汉服拍照",
      "创意市集"
    ],
    "desc": "李小龙祖居就在这片西关大屋里，走进他童年生活的地方，感受一代宗师的起点故事。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/31764f6958140a5f50cf74c72acc3473.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 122,
    "name": "天河公园",
    "rating": 4.75,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "岭南园林",
      "四季赏花",
      "相亲奇观",
      "遛娃神器",
      "晨光音乐会",
      "环湖跑道",
      "百花园",
      "历史遗迹"
    ],
    "desc": "春有宫粉紫荆如云，夏有蓝花楹成廊，秋看落羽杉染红水岸，冬赏异木棉缀粉枝头——这里一年四季都有花可追，是真正的城市花事地图。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/7707c64c-3acb-4109-a009-0cdbc6f4c4df.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 123,
    "name": "广东省博物馆",
    "rating": 4.74,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "听讲解涨知识"
    ],
    "desc": "镇馆之宝‘白切鸡’玉雕太出圈了，一块玉石雕得像刚出锅的白切鸡，细节逼真到让人惊叹，来看一眼就懂为什么全网都在讨论它。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/5afed71e-6239-460d-b1c5-dda26d682f8f.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 124,
    "name": "华南国家植物园",
    "rating": 4.74,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "萤火虫奇景",
      "见血封喉树",
      "空中栈道",
      "国家级植物园",
      "油画级景观",
      "治愈绿洲",
      "家庭野餐"
    ],
    "desc": "拥有亚洲最大温室群，四座温室如木棉花绽放，一次逛遍热带雨林、沙漠、高山与水下植物世界，堪称现实版‘地球生态圈微缩博物馆’。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/2806b224-7357-4d5c-bbef-86fe42165251.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 125,
    "name": "火炉山森林公园",
    "rating": 4.69,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "登顶看全景",
      "夜爬观星",
      "天然氧吧",
      "奇石打卡",
      "免费露营",
      "溯溪玩水",
      "四季徒步"
    ],
    "desc": "登顶白架顶，长焦镜头下天河CBD全景尽收眼底，小蛮腰清晰可见，是摄影爱好者的城中取景宝地。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/aeac42ea-16a3-43ec-aa99-fc86289169c2_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 126,
    "name": "海心沙亚运公园",
    "rating": 4.81,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "亚运主场馆",
      "小蛮腰正对面",
      "四季花海",
      "喷泉夜舞",
      "全景瞰城",
      "顶流演出地",
      "江风听歌",
      "亲子漫步",
      "海心桥上"
    ],
    "desc": "这里是2010年广州亚运会开闭幕式的举办地，走进园区仿佛穿越回那个全民沸腾的荣耀时刻，帆屏舞台、火炬塔都原样保留，历史感扑面而来。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/da84e113980e2fb89e8940adde492d44.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 127,
    "name": "花城广场",
    "rating": 4.79,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "CBD绿洲",
      "四季花海",
      "水舞光影",
      "明信片机位",
      "大师建筑群",
      "都市绿道",
      "零门槛地标"
    ],
    "desc": "被誉为广州的‘城市会客厅’，这里是现代都市与自然花海的完美融合，四周环绕着扎哈·哈迪德设计的广州大剧院、未来感十足的省博物馆‘月光宝盒’，文化地标集群本身就是一场视觉盛宴。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/5156c758-a13a-44eb-b49a-80e18785f5db_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 128,
    "name": "广州塔",
    "rating": 4.89,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "小蛮腰地标",
      "灯光秀变幻",
      "悬空观全城",
      "摩天轮看日落",
      "雪糕带回家"
    ],
    "desc": "中国第一高塔，600米直插云霄，站在云端俯瞰整座广州城，气势震撼无出其右。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/57d8bb363cb31339b0a502abaa158290.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 129,
    "name": "太古仓码头",
    "rating": 4.68,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "绝美黄昏",
      "百年仓库",
      "昼夜双面",
      "治愈步道",
      "微醺江畔",
      "花墙打卡",
      "桌游天堂"
    ],
    "desc": "傍晚五点来，看夕阳慢慢沉入珠江，红砖仓库被染成金色，江面闪着碎金，随手一拍就是电影感大片。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/80b1b28625e750e78b98eca9f966d1f3.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 130,
    "name": "海珠湖",
    "rating": 4.7,
    "district": "海珠",
    "city": "广州",
    "lat": 23.084,
    "lng": 113.317,
    "tags": [
      "城央绿心",
      "晚霞绝美",
      "环湖绿道",
      "观鸟长廊",
      "花畔塔影",
      "免费入园"
    ],
    "desc": "春天三角梅开成瀑布，秋天水杉红如火焰，四季花海不断，随手一拍都是杂志封面。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/468e70f2af32bfa4ffe65f6a93e5ca8b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 131,
    "name": "广州艺术博物院",
    "rating": 4.73,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "光影艺术建筑",
      "大师真迹",
      "自由弹琴",
      "数字水墨",
      "盖章打卡",
      "免费开放"
    ],
    "desc": "整座建筑宛如一朵在水中盛放的木棉花，鱼鳞状玻璃幕墙与45米高穹顶让阳光流淌成画，晴天来，光影随时间流动，每一刻都像走进艺术本身。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/864b0942-228e-4e78-9d23-ab3de18297f9.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 132,
    "name": "海心桥",
    "rating": 4.76,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "世界最宽人行桥",
      "广州塔最佳拍摄点",
      "日落黄金时刻",
      "江风发呆点",
      "岭南古琴设计",
      "亚洲照明大奖",
      "夜景更壮观",
      "珠江中轴步行",
      "萤火灯花池",
      "无障碍通行"
    ],
    "desc": "世界上跨度最大、宽度最宽的曲梁斜拱人行桥，走在这条‘空中丝带’上，每一步都像走在广州的未来画卷里。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/fcde1e61-cd4d-4c2d-a7d6-5ae837e5aea3_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 133,
    "name": "广州市白云山风景名胜区",
    "rating": 4.74,
    "district": "白云",
    "city": "广州",
    "lat": 23.2677,
    "lng": 113.273,
    "tags": [
      "落羽杉红叶",
      "偶遇小松鼠",
      "国产首条缆车",
      "挂红绸许愿",
      "摩星岭日落",
      "蒲谷溯溪",
      "夜爬看日出",
      "白云飞索"
    ],
    "desc": "作为‘羊城第一秀’，白云山自古就是广州的文化象征，苏轼、韩愈都曾在此留下诗篇，登高不仅看景，更是在走一段千年文脉。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/9db5bef7a96bb34012cb433b830891b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 134,
    "name": "云台花园",
    "rating": 4.8,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "罗马柱喷泉",
      "粉色风车",
      "百种玫瑰",
      "热带温室",
      "四季花开",
      "花城明珠",
      "岩石秘境"
    ],
    "desc": "一进门就能看到的罗马柱廊与音乐喷泉，水柱随节奏舞动，在阳光下折射出彩虹，仿佛置身欧洲宫廷花园，拍照格调十足。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/6f29f01a81a01d6e3127d625e2be4cd.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 135,
    "name": "广州白云湖公园",
    "rating": 4.68,
    "district": "白云",
    "city": "广州",
    "lat": 23.2677,
    "lng": 113.273,
    "tags": [
      "免费露营",
      "环湖骑行",
      "遛娃圣地",
      "涂鸦隧道"
    ],
    "desc": "傍晚时分，湖面上的摩天轮与橙紫晚霞交相辉映，氛围感拉满，无需门票就能打卡广州顶配浪漫日落，是情侣约会和拍照出片的黄金场景。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/4f9e2e4381522059a793999c2b8a6a43.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 136,
    "name": "广州市儿童公园",
    "rating": 4.74,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "夏日戏水乐",
      "全园免费玩",
      "七大主题玩",
      "草坪可露营",
      "无动力乐园",
      "地铁直达玩",
      "边玩边学",
      "童趣拍照地",
      "配套超贴心"
    ],
    "desc": "广州最大免费儿童公园，全园绝大多数项目不收费，性价比超高，遛娃不心疼钱包。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/779c0f09e78dc5093eefff3b440dbcd1.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 137,
    "name": "百花古寺",
    "rating": 4.67,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "二十四节气园林",
      "汉服拍照圣地",
      "免费开放"
    ],
    "desc": "始建于公元68年，比增城建县早133年，‘未有增城，先有百花’的民谚道尽其历史地位，是岭南文化源头的活见证。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/eab21659a662ff6a3ced12be63bf595c.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 138,
    "name": "石门国家森林公园",
    "rating": 4.67,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "自驾穿梭",
      "秋赏红叶",
      "冬日香雪",
      "云雾仙境",
      "春日花海",
      "森林浴场",
      "夏日溯溪",
      "多线可选",
      "天池日落",
      "绿野仙踪"
    ],
    "desc": "建议自驾穿行山林，一路停停走走，仿佛在自然画廊中自由漫游，每转一个弯都有新风景。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/bb86a5be-6fb3-4da2-a3b7-a77f88fe4b36_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 139,
    "name": "长洲岛",
    "rating": 4.71,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "军事教育摇篮",
      "首座廊桥水闸",
      "700年古村",
      "环岛骑行",
      "三江交汇",
      "滨江日落",
      "岭南水乡",
      "共和大道",
      "亲子露营"
    ],
    "desc": "中国近代军事教育的摇篮就在这里，走进黄埔军校旧址，仿佛穿越回百年前热血青年为理想奋斗的年代。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/70412943-0e23-4a55-b32a-91a84eece149.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 140,
    "name": "南沙游艇会",
    "rating": 4.7,
    "district": "天河",
    "city": "广州",
    "lat": 23.1292,
    "lng": 113.3623,
    "tags": [
      "《美人鱼》取景地",
      "假装在欧洲",
      "晚霞绝景",
      "帆船观光",
      "豪华游艇群",
      "海风晚餐"
    ],
    "desc": "",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a1cd7781-b5d0-4346-83ed-6cc464bbfa8a.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 141,
    "name": "深圳欢乐谷",
    "rating": 4.67,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "异域拍照"
    ],
    "desc": "💡\n夏日必冲玛雅水公园，巨浪风暴造浪池与彩虹滑道组合，清凉刺激一夏。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/77391af7-cb4d-4e64-a2ce-03b74dd4b96b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 142,
    "name": "海上世界",
    "rating": 4.79,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "光影水舞",
      "环球美食",
      "滨海漫步",
      "艺术海岸",
      "亲子草坪",
      "夜生活街"
    ],
    "desc": "",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/f74639bd51130131b66e45a098012db3.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 143,
    "name": "塘朗山公园",
    "rating": 4.72,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "野生猕猴",
      "免费开放",
      "日落熔金",
      "徒步登山",
      "青云台",
      "地铁直达"
    ],
    "desc": "💡\n深圳十峰之一，海拔432米，登顶极目阁可280度俯瞰深圳湾与香港岛，城市山海画卷一目了然。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/22db77fb-86ff-43fa-8dfe-f470c7fb2676.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 144,
    "name": "南头古城",
    "rating": 4.7,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "深港澳源头",
      "光影穿越",
      "随手出片",
      "黑胶工厂",
      "灯光夜景"
    ],
    "desc": "💡\n深圳的‘城市原点’，1700年历史的岭南重镇，曾管辖深港澳三地，是名副其实的‘深港澳文化源头’。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a0f01414f7f8e114231e7e396c05303b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 145,
    "name": "深圳世界之窗",
    "rating": 4.79,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "一天环游世界",
      "烟花秀",
      "打铁花",
      "登塔俯瞰",
      "全家同乐",
      "魔法街景",
      "夜场畅玩",
      "精彩演出",
      "出站即达"
    ],
    "desc": "💡\n一天之内打卡埃菲尔铁塔、金字塔、自由女神像等130多个世界地标，仿佛真的环游了全球一圈。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/408609e2d1bb33813e26ee64cb841783.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 146,
    "name": "南山博物馆",
    "rating": 4.75,
    "district": "南山",
    "city": "深圳",
    "lat": 22.5312,
    "lng": 113.9299,
    "tags": [
      "🏷️",
      "光影墙拍照",
      "多语种讲解"
    ],
    "desc": "💡\n作为全国规模最大的区县级博物馆之一，馆藏8000余件文物，系统呈现从古越文明到改革开放的完整脉络，是理解深圳文化根基的权威窗口。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/89da2d7d79a6472f15170e5aa0253536.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 147,
    "name": "华侨城欢乐海岸",
    "rating": 4.72,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "遛娃天堂",
      "湖光夜影",
      "摩天轮落日",
      "湖景美食",
      "环湖漫步"
    ],
    "desc": "💡\n傍晚时分在湖畔散步，欧式建筑倒映水中，灯光渐次亮起，随手一拍就是大片，氛围感直接拉满。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/1feeafb54534d14bbe94eacfb4efe991.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 148,
    "name": "深圳湾公园",
    "rating": 4.92,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "海风骑行",
      "海鸥雪",
      "最美地铁口",
      "爱心水洼",
      "橘子海",
      "日出剧场",
      "紫色花海",
      "春笋同框"
    ],
    "desc": "💡\n被誉为深圳最舒服的滨海骑行道，共享单车直达，沿海平路无坡，一边是红树林滩涂飞鸟，一边是高楼林立的城市天际线，吹着海风骑完全程超治愈。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/967e9d90-4aa8-4b10-b5da-85143e4c258a.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 149,
    "name": "前海石公园",
    "rating": 4.79,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "绝美日落",
      "时代地标",
      "草坪野餐",
      "滨海步道",
      "摩天轮打卡",
      "公园贯通",
      "城市绿洲",
      "海边礁石"
    ],
    "desc": "💡\n深圳看日落的顶流打卡地，傍晚时分天空被染成橙红，海面波光与摩天轮交相辉映，随手一拍就是电影感大片。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/236e7d9fe79ac628538968f88c26e46d.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 150,
    "name": "莲花山公园",
    "rating": 4.78,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "改革开放地标",
      "免费观景台",
      "粉色花海",
      "夜景星河",
      "印象派光影",
      "大草坪",
      "懒人友好"
    ],
    "desc": "",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/854b10d784c2e2777c08e24a8a6959aa.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 151,
    "name": "笔架山公园",
    "rating": 4.73,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "俯瞰CBD",
      "5G步道",
      "免费露营",
      "玩水捞鱼"
    ],
    "desc": "💡\n登上笔冠峰，福田CBD摩天楼群尽收眼底，平安金融中心近在咫尺，傍晚登顶还能一次看尽夕阳与夜景，随手一拍就是城市大片。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/91ae440d19ef2bcef9ff1f18ec4a40d3.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 152,
    "name": "塘朗山公园",
    "rating": 4.72,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "野生猕猴",
      "免费开放",
      "日落熔金",
      "徒步登山",
      "青云台",
      "地铁直达"
    ],
    "desc": "💡\n深圳十峰之一，海拔432米，登顶极目阁可280度俯瞰深圳湾与香港岛，城市山海画卷一目了然。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/22db77fb-86ff-43fa-8dfe-f470c7fb2676.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 153,
    "name": "深圳国际园林花卉博览园",
    "rating": 4.73,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "古风穿越",
      "精华路线",
      "亲子乐园"
    ],
    "desc": "💡\n无需出国也能逛遍世界园林，从江南水乡到日式枯山水，从徽派白墙到尼泊尔花园，近百处微缩景观浓缩成一场环游世界的步行之旅。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/b1915dc6-9b76-41e2-b785-001c5781dd57.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 154,
    "name": "香蜜公园",
    "rating": 4.68,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "树冠栈道",
      "炮仗花海",
      "遛娃天堂",
      "都市氧吧",
      "文化季",
      "运动圣地",
      "儿童艺术小镇",
      "草坪野餐",
      "湖上泛舟"
    ],
    "desc": "💡\n8.8米高的空中栈道穿梭在荔枝林冠层，边走边摸得到树叶，还能俯瞰城市与绿林交织的壮丽全景，清晨和傍晚尤其震撼。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/29261125ec5746410a07010b6cf2f68d.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 155,
    "name": "深圳博物馆同心路馆(古代艺术)",
    "rating": 4.68,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "免费亲子游"
    ],
    "desc": "💡\n全国少有的‘从顶楼往下逛’的博物馆，乘坐科幻感十足的胶囊电梯开启观展之旅，动线设计巧妙，一路向下不走回头路，舒适又高效。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/5b01d87440be4a5a129488552feed9fc.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 156,
    "name": "阳台山森林公园",
    "rating": 4.69,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "云海日落",
      "城中氧吧",
      "天然健身房"
    ],
    "desc": "💡\n深圳西部最高峰，海拔587.1米的大阳台山顶，登顶后可270°俯瞰深圳三区交界，远眺东莞、内伶仃岛，天气好时连‘春笋’和平安大厦都清晰可见，城市与山林在此交汇。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/26965a73-e0bf-4b20-8e03-45dfb30dbde5.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 157,
    "name": "凤凰山森林公园",
    "rating": 4.75,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "求姻缘灵验",
      "低难度登山",
      "天然空调",
      "望烟楼看日落",
      "亲子一站式",
      "城市绿肺",
      "明清古村",
      "祈愿牌长廊",
      "全年免费"
    ],
    "desc": "💡\n半山腰的凤岩古庙香火极旺，是深圳四大古庙之一，本地人常来求姻缘、学业、平安，许愿树挂满红绸带，氛围感十足。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a148effb-ecc7-4e85-b54a-0d89ba85479b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 158,
    "name": "宝安西湾红树林公园",
    "rating": 4.72,
    "district": "宝安",
    "city": "深圳",
    "lat": 22.7206,
    "lng": 113.883,
    "tags": [
      "🏷️",
      "赶海抓小蟹",
      "滨海骑行道",
      "遛娃省心",
      "人少景幽",
      "全年免费"
    ],
    "desc": "💡\n晴天傍晚，站在滨海栈道上，看飞机低空划过燃烧的落日，跨海大桥车流化作光带，海风拂面，仿佛置身电影画面。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/dbc19e22934b37d629755abffba6d2b1.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 159,
    "name": "石岩湿地公园",
    "rating": 4.68,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "骑行天花板",
      "露营自由",
      "候鸟驿站",
      "遛娃圣地",
      "晚霞出片",
      "星空营地",
      "禾雀花廊",
      "生态博物馆"
    ],
    "desc": "💡\n深圳少数允许搭帐篷的公园之一，大片草坪平整开阔，可野餐、放风筝、泡茶聊天，是家庭周末露营的理想选择。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/76d934668b68192fce2a9bcd30761666.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 160,
    "name": "欢乐港湾",
    "rating": 4.8,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "湾区之光",
      "光影水秀",
      "临海步道",
      "童乐园",
      "钟书阁",
      "江边餐厅",
      "免费入园",
      "地铁直达"
    ],
    "desc": "💡\n傍晚乘坐摩天轮，从黄昏渐变的天空到城市华灯初上，全程30分钟仿佛在云端追光，邂逅一场温柔的日落告白，随手一拍都是电影感大片。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/525f98acb7e5c23857cb1311de9117a4.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 161,
    "name": "广东梧桐山风景名胜区(暂停开放)",
    "rating": 4.76,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "鹏城第一峰",
      "十里杜鹃花海",
      "云海日出",
      "凌云道陡阶",
      "好汉坡挑战",
      "空中岛屿",
      "俯瞰盐田港",
      "丛林秘境",
      "360°全景",
      "城市绿肺"
    ],
    "desc": "💡\n每年2月至4月，十里杜鹃道变身粉色花海，吊钟花与映山红次第盛开，是深圳春季最浪漫的徒步路线。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/e39ce195f8930d2fe828dcacfc2c59e5.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 162,
    "name": "洪湖公园",
    "rating": 4.77,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "华南最大荷塘",
      "清晨仙气栈道",
      "古风出片圣地",
      "遛娃一站式",
      "杉林如画",
      "书吧观荷",
      "环湖氧吧"
    ],
    "desc": "💡\n清晨6点入园，荷花正盛放，喷雾系统开启，仙气缭绕的栈道宛如水墨画中行走，是拍出无滤镜大片的黄金时段。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/5e59a8c1-e318-4ace-bebc-c85d27a7e734_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 163,
    "name": "深圳仙湖植物园",
    "rating": 4.75,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "植物王国",
      "落羽红杉",
      "沙漠温室",
      "隐秘打卡",
      "森系大片",
      "活化石林",
      "湖上栈道",
      "禅意庭院",
      "接驳畅游"
    ],
    "desc": "",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/d9159e53-8026-4f76-aa92-b3dbd7fd28fe_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 164,
    "name": "大鹏所城",
    "rating": 4.68,
    "district": "大鹏",
    "city": "深圳",
    "lat": 22.5768,
    "lng": 114.4828,
    "tags": [
      "🏷️",
      "鹏城之根",
      "三代五将",
      "古宅咖啡",
      "越夜越精彩",
      "城海联动",
      "登城墙",
      "经典路线"
    ],
    "desc": "💡\n深圳的别称‘鹏城’就源自这里，走进这座600年历史的海防要塞，就像翻开城市最早的史书。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/85ad6bf67aaa25ebaf519b56892f86d1.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 165,
    "name": "大芬油画村",
    "rating": 4.7,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "随手出片",
      "手把手教学",
      "油画第一村",
      "免费看展",
      "艺术盲盒",
      "亲民价格"
    ],
    "desc": "💡\n走进村口就像闯进调色盘世界，墙上的巨幅涂鸦、巷子里的彩绘、满街的油画，随手一拍就是艺术感大片，拍照党千万别错过。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/f8a17efd-7cbe-4753-a7b6-fff8d20aa8ad.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 166,
    "name": "甘坑古镇",
    "rating": 4.7,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "三百年围屋",
      "清代炮楼",
      "三角梅瀑布",
      "汉服换装",
      "围炉煮茶",
      "家风家训",
      "亲子农耕",
      "免费博物馆"
    ],
    "desc": "💡\n被誉为现实版《千与千寻》，夜晚灯笼亮起，古建筑群在光影中宛如幻境，穿汉服漫步其中，仿佛穿越到宫崎骏的动画世界。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/b54723e9326bb0d059d2e5d65e1b16fe.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 167,
    "name": "大梅沙海滨公园",
    "rating": 4.81,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "蓝眼泪奇观",
      "栈道拍大片",
      "心形石秘境",
      "畅游安全区",
      "橘子海日落",
      "海上跳伞",
      "出站即沙滩",
      "赤脚踩沙",
      "天长地久石"
    ],
    "desc": "💡\n深圳唯一的5A级免费海滨公园，1.8公里黄金沙滩随便踩，不用预约随时冲进海里游泳，性价比太高了。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/1c13fbee-ea6d-45f8-9738-9f4dffe17118.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 168,
    "name": "虹桥公园",
    "rating": 4.72,
    "district": "福田",
    "city": "深圳",
    "lat": 22.5228,
    "lng": 114.0595,
    "tags": [
      "🏷️",
      "4公里红桥",
      "全景塔观景",
      "免费开放",
      "晨雾仙境",
      "环湖骑行",
      "滑板天堂",
      "三桥连走",
      "亲子乐园",
      "天然氧吧"
    ],
    "desc": "💡\n4公里长的红色空中栈道，像一条巨龙盘踞在山林之上，行走其上仿佛置身画中，随手一拍就是大片。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/cd467f68b0435e0b9658c75a616b1022.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 169,
    "name": "下埔滨江公园",
    "rating": 4.43,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "江畔夜画",
      "老城生活图景",
      "江边听歌",
      "城市客厅",
      "宠物夜灯道",
      "免费滨江绿洲",
      "功能分区清晰",
      "雨后江风"
    ],
    "desc": "夜幕降临时，摩天轮的灯光在江面投下流动星河，游乐设施化作童话里的发光城堡，沿着亲水步道散步，仿佛走入一幅现代滨水夜画。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/2e53d42cb5452383dd9de2535f93f54b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 170,
    "name": "东江沙公园",
    "rating": 4.52,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "江边露营",
      "江畔日落",
      "天然沙滩",
      "玻璃桥",
      "景观塔",
      "亲子乐园",
      "观景挑台"
    ],
    "desc": "江边0元野炊露营圣地，水清沙幼还能烧烤，人少景美像包场，周末逃离人群就来这躺平吹江风。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/aea3865ac1b6fc203e775361d3eeb2d3.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 171,
    "name": "合江楼",
    "rating": 4.57,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "苏东坡曾居",
      "两江交汇处",
      "夜景亮灯",
      "贬官破例入住",
      "免费登顶",
      "四面观景"
    ],
    "desc": "苏东坡被贬惠州时曾暂居于此，写下多首诗篇，走进合江楼就像走进一段鲜活的文人往事。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/f2a6daf66f78f87dcfbbc4d01f762ba.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 172,
    "name": "惠州西湖风景名胜区",
    "rating": 4.8,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "5A免门票",
      "夜游如仙侠",
      "登塔瞰五湖",
      "九曲桥夜灯"
    ],
    "desc": "苏东坡曾在此生活三年，写下多篇诗文，漫步西湖仿佛走进他笔下的岭南诗意画卷。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/280ea51a6e5e3de2e528ab575b039634.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 173,
    "name": "金山湖公园",
    "rating": 4.46,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "拍照出片",
      "落羽杉变红",
      "全家各得其乐",
      "玩购一体",
      "环湖跑道",
      "三角梅盛开",
      "湖光夜色",
      "仿古廊桥",
      "乘船游湖",
      "双彩虹"
    ],
    "desc": "超大草坪+清澈湖景，拍照随便一拍就是朋友圈高赞大片，绿意与水光交织，出片率超高。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/1336960a2cd5bc748b8ee8baff969a16.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 174,
    "name": "惠州植物园",
    "rating": 4.67,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "遛娃天花板",
      "全民免费",
      "潘多拉星球",
      "四季皆景",
      "光影绝美",
      "徒步减压"
    ],
    "desc": "出片率100%的温室必须冲！透明穹顶+空中栈道，随手一拍就是新加坡樟宜机场同款科幻感，热带雨林区雾气缭绕像闯进绿野仙踪，多肉区仙人掌比人高，张张都是ins风大片。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a0fe978b97db7e664a5157e93cae7ddb.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 175,
    "name": "惠州鹿江公园",
    "rating": 4.44,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "草坪野餐",
      "遛娃天堂",
      "全龄运动"
    ],
    "desc": "穿条小裙子来拍欧式大教堂，光影柔和的下午4-5点，随手一拍就是童话大片。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/ae6f8066218eea79ec1d338f54efebf4.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 176,
    "name": "东坡祠",
    "rating": 4.53,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "最大纪念馆",
      "木棉盛景",
      "亲子研学",
      "穿越感",
      "岭南园林"
    ],
    "desc": "春天木棉花开满园红艳，古建筑配红花，随手一拍就是诗意大片，是本地人私藏的赏花秘境。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/1a96d340d73bb7e8b0788849e27218df.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 177,
    "name": "千花洲度假区",
    "rating": 4.54,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "四季花海",
      "无动力乐园",
      "魔幻夜景",
      "萌宠投喂",
      "簕杜鹃海",
      "环湖小火车",
      "月季迷宫",
      "恐龙世界",
      "绿道骑行",
      "公仔巡游"
    ],
    "desc": "五六百亩花海四季轮放，不同季节都有花可赏，堪称现实版桃花源。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/37f56444d00a089bb46a96ca7cd1524e.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 178,
    "name": "九龙峰谭公祖庙",
    "rating": 4.44,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "明代古庙",
      "九龙盘山",
      "初六祈福",
      "松影古木",
      "尖笔峰",
      "云雾缭绕"
    ],
    "desc": "始建于明代的谭公祖庙，是惠州地区香火最旺的民间信仰圣地之一，感受千年民俗的活态传承。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/640639f9d55e201f4672ada6a3a51996.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 179,
    "name": "巽寮湾风景区",
    "rating": 4.74,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "赶海抓螃蟹",
      "玻璃海浮潜",
      "小镰仓公路",
      "落日熔金",
      "双月奇观",
      "水上飞人",
      "亿年奇石",
      "途经三岛"
    ],
    "desc": "乘快艇15分钟直达三角洲岛，清澈见底的玻璃海中浮潜，能看到珊瑚和热带鱼群，仿佛置身热带海岛。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/9fe6f0e541f646ab60ca698147055ce1.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 180,
    "name": "双月湾",
    "rating": 4.74,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "海龟保护区",
      "蓝眼泪",
      "观景台",
      "赶海挖贝",
      "会仙桥",
      "冲浪体验",
      "浮潜探海",
      "礁石酒吧"
    ],
    "desc": "全球仅两处的‘双湾奇景’：大亚湾平静如镜，红海湾波涛汹涌，从高空俯瞰宛如两轮新月镶嵌海岸，一次打卡两种极致海景。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a5d3f961681e57978711d3c3dd198ea8.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 181,
    "name": "无名海滩",
    "rating": 4.46,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "赶海收获多",
      "蓝绿秘境",
      "日落美景",
      "免费露营",
      "人少安静",
      "海边寻宝",
      "说走就走"
    ],
    "desc": "退潮后沿着礁石滩往前走，潮间带随处可见热带小鱼、青口、辣螺和小螃蟹，带娃赶海超有成就感。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/946d0614ba747bcfc20407fc478547a3.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 182,
    "name": "狮子岛",
    "rating": 4.44,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "果冻海",
      "现实版动森",
      "日落剪影",
      "听海入眠",
      "广东小马尔代夫",
      "守护传说",
      "天然石狮",
      "可冲浪"
    ],
    "desc": "退潮后可以登上形似卧狮的巨型礁石，像探险一样打卡‘沉睡的狮子’，传说这头狮子守护着海岸的安宁。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/b37c808d44c1ee04a1e2dc5f0e3d355b.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 183,
    "name": "黑排角",
    "rating": 4.53,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "黑色礁石海岸",
      "天空之境",
      "抓小螃蟹",
      "鱼纹型长浪",
      "免费秘境"
    ],
    "desc": "黑色玄武岩礁石与湛蓝海水形成强烈对比，随手一拍就是大片，完全不同于普通沙滩的地质奇观。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/ef5725dae70da33aef4fe090358a61cd.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 184,
    "name": "十里银滩",
    "rating": 4.5,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "日落余晖",
      "亲子戏水",
      "清晨漫步",
      "水上摩托"
    ],
    "desc": "绵延五公里的银白沙滩，沙质细腻如粉，海水清澈湛蓝，被誉为‘广东马尔代夫’，是家庭度假和情侣拍照的理想之地。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/10192488f3e6b0ab40edc577fb6b0e4f.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 185,
    "name": "清泉古寺",
    "rating": 4.47,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "双泉夹墙",
      "依山面海",
      "吃斋饭",
      "拍照出片"
    ],
    "desc": "建于清朝顺治年间的观音道场，已有370年历史，是大亚湾地区最具影响力的佛教圣地之一。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/57354050a616d89b522086f59aafe5a2.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 186,
    "name": "大亚湾红树林城市湿地公园",
    "rating": 4.43,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "亲子自然课",
      "生态基因库",
      "天然遮阳伞",
      "桨板穿绿林",
      "俯瞰湿地城",
      "邂逅白鹭"
    ],
    "desc": "带孩子走进免费的自然课堂，红树林栈道边有科普展板和互动馆，边走边学，招潮蟹、弹涂鱼、白鹭都成了活教材，寓教于乐超省心。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/202ebacf1b35e73be649c1013c09e0da.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 187,
    "name": "亚公顶森林公园",
    "rating": 4.53,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "俯瞰大亚湾",
      "天然氧吧",
      "山顶看日落",
      "免费开放",
      "登山有挑战",
      "亲子出游",
      "夜爬体验",
      "山脚有小吃"
    ],
    "desc": "登上306米高的山顶，一眼望尽大亚湾的壮阔海景与淡水城区的繁华全景，视野开阔得让人心旷神怡。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a0d7137c3cca0cda37214aa788e48bbe.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 188,
    "name": "滨海公园",
    "rating": 4.46,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "渔港夜景",
      "随手出片",
      "放空发呆",
      "免费看海",
      "真实海景",
      "轻松遛娃"
    ],
    "desc": "傍晚沿着海岸线散步，吹着咸湿海风，看渔船归航、渔火点点，整个人都安静下来了。",
    "free": true,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a324499b9091e1dca91010bf2f6c9760.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 189,
    "name": "大亚湾",
    "rating": 4.6,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "退潮捡贝壳",
      "看日出胜地",
      "荧光海奇观",
      "山海骑行道",
      "细软白沙",
      "快艇出海",
      "滨海摄影道",
      "海水清澈"
    ],
    "desc": "退潮后沙滩上密布小贝壳，弯腰就能捡到一捧，孩子玩得不想走。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/4a9e07d40b7f6bff9c95aacc61fa535e.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 190,
    "name": "石湾公园",
    "rating": 4.48,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "湖畔散步",
      "陶艺文化",
      "亲子同乐",
      "登高观景",
      "音乐喷泉"
    ],
    "desc": "环湖栈道与柳树成荫的湖畔步道相连，清晨或傍晚牵手散步，吹着江风，惬意又悠闲。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/d6b639478ed089056db0a6e6d7b128b2.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 191,
    "name": "罗浮山风景名胜区",
    "rating": 4.66,
    "district": "惠东",
    "city": "惠州",
    "lat": 22.9844,
    "lng": 114.7198,
    "tags": [
      "飞云顶登顶",
      "雨后云海",
      "葛洪炼丹处",
      "夜爬看日出",
      "天然氧吧",
      "道教洞天",
      "家庭轻松线",
      "千年银杏"
    ],
    "desc": "作为‘岭南第一山’，罗浮山自古就是文人墨客笔下的仙境，苏轼曾写下‘罗浮山下四时春’，文化底蕴深厚，值得亲自走一遭。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/d1532639bbf496777366a14d0393e005.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 192,
    "name": "曼斗佛寺",
    "rating": 4.41,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "千年古寺",
      "千灯供佛",
      "金塔日出",
      "早课早餐",
      "写贝叶经"
    ],
    "desc": "始建于公元950年的傣族古寺，是曼斗村寨历史与信仰的活化石，承载着千年南传佛教文化。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/7b1bcbe59d63baa18630e24af41c86da.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 193,
    "name": "西双版纳原始森林公园",
    "rating": 4.48,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "百只孔雀齐飞",
      "泼水节狂欢",
      "丛林飞跃",
      "板根奇观",
      "喂猴子互动",
      "高空栈道"
    ],
    "desc": "亲眼见证数百只绿孔雀从山林滑翔而下，掠过湖面，羽翼在阳光下闪耀如金，这是国内罕见的‘孔雀东南飞’实景，震撼场面堪比自然纪录片。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a5752b062d29c7d7e2db80d25feb3a7f.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 194,
    "name": "基诺山寨景区",
    "rating": 4.43,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "尝酸蚂蚁",
      "边走边学",
      "雨林大餐",
      "鼓声迎新",
      "鼓震山谷",
      "荡过绿意",
      "亲手割胶"
    ],
    "desc": "中国最后一个被确认的少数民族聚居地，走进基诺族‘直过民族’的千年文化现场，感受从原始社会直接跨入现代的文明奇迹。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/5900a7dcbc8879757131eb945d48f7e4.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 195,
    "name": "西双版纳傣族园",
    "rating": 4.68,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "活态民族博物馆",
      "千年佛寺",
      "拍照出片",
      "寨中美食",
      "自由孔雀"
    ],
    "desc": "每天两场泼水狂欢，不用等到四月也能感受泼水节的祝福与激情，现场氛围像大型蹦迪现场，提前带好换洗衣物，冲进水花里释放压力。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/223d60a9f60234ed5640620fa77404d7.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 196,
    "name": "西双版纳热带花卉园",
    "rating": 4.64,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "凤凰花盛开",
      "会跳舞的草",
      "边玩边学",
      "割胶演示"
    ],
    "desc": "亲眼见证会随音乐摆动的跳舞草，还有能承载一个小孩的巨型王莲，这些课本里的神奇植物在这里都能真实触摸。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/5e8b6332-6fcc-4f3d-8837-afaa0afe66cb.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 197,
    "name": "西双版纳总佛寺",
    "rating": 4.59,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "千年佛寺",
      "金顶佛殿",
      "竹编大佛",
      "金身立佛",
      "傣王白塔",
      "金龙盘阶",
      "祈福仪式",
      "风铃菩提"
    ],
    "desc": "作为西双版纳最古老的南传佛教寺院之一，已有千年历史，在东南亚佛教圈享有盛誉，踏入其中仿佛走进一部活着的信仰史。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/ffd832a0-bbc2-4566-9c45-eb20e214ceb7_edit.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 198,
    "name": "西双版纳滨江公园",
    "rating": 4.37,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "老艺人表演",
      "拍照圣地",
      "本地节奏"
    ],
    "desc": "傍晚沿着澜沧江木栈道散步，江风拂面，远处是告庄夜市的灯火，本地老人在拉二胡，孩子在喂鸽子，这才是西双版纳的真实生活。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/c776d95c90fedb46da8a8f60d8b59d34.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 199,
    "name": "西双版纳勐泐文化旅游区",
    "rating": 4.37,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "坐佛形布局",
      "孔雀放飞",
      "泼水祈福",
      "玻璃观景台"
    ],
    "desc": "在千年傣王皇家寺院遗址上重建，感受南传佛教与傣族王朝的历史回响",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/a9a1766674f486f93e3927100bd97e74.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 200,
    "name": "曼听御花园景区",
    "rating": 4.82,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "千年王室行宫",
      "佛寺共园",
      "万人放水灯",
      "总理足迹",
      "贝叶棕迷宫"
    ],
    "desc": "",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/fd60dbe0134546f8b4b630cc4ae8acab.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 201,
    "name": "中缅第一寨勐景来景区",
    "rating": 4.39,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "综艺取景地",
      "独树成林",
      "边境田园画",
      "活态文化馆",
      "古法造纸",
      "热带果园村"
    ],
    "desc": "一脚跨两国！在229号界碑旁啃着菠萝，看缅甸山头飘来的云，真实体验中缅边境的日常诗意。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/fbcc744cc9ba50f4a0096df33f17a875.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 202,
    "name": "打洛国门景区",
    "rating": 4.38,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "触摸国境线",
      "最近陆路通道",
      "独树成林",
      "尝鲜缅甸冷饮",
      "边境烟火气",
      "边贸驿站",
      "绿意徒步",
      "雨中打卡"
    ],
    "desc": "站在国门之下，孩子第一次亲手触摸界碑，激动地喊‘我出国啦！’，边境仪式感拉满。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/acba527e4abd6b2535c0fd20b02a8bc5.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 203,
    "name": "中国科学院西双版纳热带植物园",
    "rating": 4.78,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "中科院科普",
      "绞杀榕震撼",
      "棕榈园大片",
      "含羞草互动",
      "东西两区"
    ],
    "desc": "中国面积最大、物种最丰富的热带植物园，13000多种植物在此共生，堪称‘热带雨林的基因库’，国家级科研重镇的生态典范。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/e2eec773d0c94af4ed08445de5e6eff0.jpeg"
  },
  {
    "emoji": "🌳",
    "id": 204,
    "name": "西双版纳热带雨林国家公园望天树景区",
    "rating": 4.55,
    "district": "景洪",
    "city": "西双版纳",
    "lat": 22.0097,
    "lng": 100.7975,
    "tags": [
      "北纬21°绿洲",
      "空中绿海穿行",
      "水陆空全玩",
      "东方亚马逊",
      "雨林生存解密",
      "仰望参天树",
      "夜遇萤火虫",
      "自然研学课",
      "生命奇迹树",
      "童话花径"
    ],
    "desc": "这里是北纬21°唯一的完整热带雨林绿洲，拥有中国最大望天树群落，最高达80米，堪称地球北回归线上的生态奇迹。",
    "free": false,
    "image": "https://aos-comment.amap.com/UKFN9HT2M870QV5A_AIGC/e35225c493a40146d5d469ef4c9fd737.jpeg"
  }
]